name: Generate snake animation

permissions:
  contents: write

on:
  schedule:
    - cron: "0 */12 * * *" # a cada 12 horas
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: MiltonAlbuquerque
          outputs: dist/snake.svg?color_snake=#00F7FF&color_dots=#161B22,#0e1a2b,#1f6feb,#58a6ff,#79c0ff

      - name: Push snake to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output
